#!/bin/sh

VIMFILES=Dropbox/Dotfiles/common/vim
VIMRCDIR=$HOME/.vimrc
VIMDIR=$HOME/.vim


if [ -L $VIMDIR ];
then
    rm $VIMDIR
fi

if [ -L $VIMRCDIR ];
then
    rm $VIMRCDIR
fi

ln -s $HOME/$VIMFILES $VIMDIR
ln -s $HOME/$VIMFILES/vimrc $VIMRCDIR

vim +BundleInstall +qall
npm install ~/.vim/bundle/tern_for_vim
