#!/usr/bin/env bash

VENDORS=(

  git@github.com:mileszs/ack.vim
  git@github.com:ervandew/supertab.git
  git@github.com:godlygeek/tabular.git
  git@github.com:SirVer/ultisnips.git
  git@github.com:exu/vim-ultisnips-snippets.git
  git@github.com:pangloss/vim-javascript.git
  git@github.com:scrooloose/nerdtree.git
  git@github.com:scrooloose/syntastic.git
  git@github.com:timcharper/textile.vim.git
  git@github.com:tpope/vim-cucumber.git
  git@github.com:tpope/vim-fugitive.git
  git@github.com:tpope/vim-git.git
  git@github.com:tpope/vim-haml.git
  git@github.com:tpope/vim-markdown.git
  # git@github.com:tpope/vim-rails.git
  git@github.com:tpope/vim-surround.git
  git@github.com:tsaleh/vim-matchit.git
  git@github.com:tomtom/tcomment_vim.git
  git@github.com:vim-ruby/vim-ruby.git
  git@github.com:mattn/webapi-vim.git
  git@github.com:mattn/gist-vim.git
  git@github.com:vim-scripts/vimwiki.git
  git@github.com:vim-scripts/bufexplorer.zip.git
  git@github.com:vim-scripts/mru.vim.git

  git@github.com:groenewege/vim-less.git
  # git@github.com:hail2u/vim-css3-syntax.git
  # git@github.com:skammer/vim-css-color.git

  git@github.com:mattn/emmet-vim.git

  git@github.com:Raimondi/delimitMate.git
  git@github.com:Lokaltog/vim-powerline.git
  git@github.com:vim-scripts/dbext.vim.git
  git@github.com:jceb/vim-orgmode.git
  git@github.com:vim-scripts/utl.vim.git
  git@github.com:exu/pgsql.vim.git
  git@github.com:exu/symfony_menu.vim.git
  git@github.com:exu/img2data.vim.git
  git@github.com:othree/html5.vim.git
  # git@github.com:exu/PIV.git
  # git@github.com:exu/vim-python_koans.git
  git@github.com:stephpy/vim-php-cs-fixer.git
)


function default {
    echo "Usage:"
    echo "--------------------------------------------------------------------------------"
    echo "./vendors [reinstall|update]"
}

function reinstall {
    for vendor in "${VENDORS[@]}"
    do
        cd ~/.vim/
        name="${vendor#*/}"
        name="${name/.git/}" #i didn't find how to make it in one command
        destination="./bundle/${name}"
        if [ -d "$destination" ]; then
            rm -rf $destination
        fi
        git clone --depth=1 $vendor $destination
    done
}

function update {
    for vendor in "${VENDORS[@]}"
    do
        cd ~/.vim/
        name="${vendor#*/}"
        name="${name/.git/}" #i didn't find how to make it in one command
        destination="./bundle/${name}"
        cd $destination
        git pull --depth=1
    done

    cd ~/.emacs.d/
}

case "$1" in
    "reinstall") reinstall ;;
    "update") update ;;
    *) default ;;
esac
